import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Sidebars configuration for documentation.
 *
 * - guidesSidebar, specsSidebar, decisionsSidebar use autogenerated sidebars
 *   from their respective directories.
 * - skillsSidebar is built from skills/_index.json so the manifest is the
 *   single source of truth for ordering. Reordering or regrouping the
 *   manifest immediately reorders the rendered sidebar on the next build.
 *
 * Governing: ADR-0029, SPEC-0021 REQ "Routing, Sidebar, and Navbar".
 */
function buildSkillsSidebar(): any[] {
  const manifestPath = path.join(__dirname, '../skills/_index.json');
  if (!fs.existsSync(manifestPath)) {
    return [{type: 'doc', id: 'skills/index', label: 'Overview'}];
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8')) as Record<string, string[]>;
  const items: any[] = [
    {type: 'doc', id: 'skills/index', label: 'Overview'},
  ];

  for (const [groupName, names] of Object.entries(manifest)) {
    items.push({
      type: 'category',
      label: groupName,
      collapsed: false,
      items: names.map((name) => ({
        type: 'doc',
        id: `skills/${name}`,
        label: name,
      })),
    });
  }

  return items;
}

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  skillsSidebar: buildSkillsSidebar(),
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  decisionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'decisions',
    },
  ],
};

export default sidebars;
